blog/urls.py
"""Defines URL patterns for blog."""

from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # About page
    path('about/', views.about, name='about'),
    # Individual Post Page
    path('posts/<int:post_id>/', views.post, name='post')
]

sloth_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.


class Author(models.Model):
    full_name = models.CharField(max_length=100)

    def __str__(self):
        return self.full_name


class Post(models.Model):
    headline = models.CharField(max_length=200)
    tagline = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)
    # content = models.TextField()
    # adding ckeditor rich text field instead of built in text field
    content = RichTextField()

    def __str__(self):
        return self.headline

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Post

# Create your views here.


def index(request):
    """The home page of the blog that lists all posts."""
    posts = Post.objects.order_by('-pub_date')
    context = {'posts': posts}
    return render(request, 'blog/index.html', context)


def post(request, post_id):
    """Show a single post and all its content."""
    post = Post.objects.get(id=post_id)
    context = {'post': post}
    return render(request, 'blog/post.html', context)


def about(request):
    """A page detailing information about myself."""
    return render(request, 'blog/about.html')

blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}

<div class="about">
    <h1>About Me</h1>
    <p>Whoops. Didn't expect anyone to click on this. This is embarrasing... This page is still under construction,
        check back later!</p>
</div>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>AwkwardSloth</title>
    <meta charset="UTF-8">
    <meta name="copyrighted-site-verification" content="fcad0b5a4e1cf159" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<header>
    <p class="site-title">
        <a href="{% url 'blog:index' %}">AwkwardSloth</a>
    </p>
    <p class="tagline">a comics blog.</p>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">Home</a></li>
            <li><a href="{% url 'blog:about' %}">About</a></li>
        </ul>
    </nav>
</header>
{% block content %}{% endblock content %}

<footer>
    <p>&copy;2020 AwkwardSloth</p>
</footer>

</html>

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}

{% load markdown_extras %} 

{% for post in posts %}
    <article>
        <div class="info">
            <h1>{{ post.headline }}</h1>
            <h2 class="tagline">{{ post.tagline }}</h2>
            <h3>By {{ post.author }} | {{ post.pub_date }}</h3>
        </div>
        <p>{{ post.content | markdown | safe }}</p>
    </article>
{% empty %}
    <p>No Posts.</p>
{% endfor %}
<footer>
    <p>&copy;2020 AwkwardSloth</p>
</footer>
{% endblock content %}

blog/templates/blog/post.html
{% extends "blog/base.html" %}

{% block content %}

{% load markdown_extras %}

<article>
    <div class="info">
        <h1>{{ post.headline }}</h1>
        <h2 class="tagline">{{ post.tagline }}</h2>
        <h3>{{ post.author }} | {{ post.pub_date }}</h3>
    </div>
    <p>{{ post.content | markdown | safe}}</p>
</article>




{% endblock content %}